# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit_slr_cpp <- function(x, y) {
    .Call('_SLR_fit_slr_cpp', PACKAGE = 'SLR', x, y)
}

